### ISSUE TITLE
Latest release for PI Zero / Build on pi zero

### ISSUE THREAD

**Issue by fbeauche** [nymea/nymea-networkmanager#25]
I followed the instructions described in : 
https://github.com/nymea/berrylan/issues/10

It seems the "rasbian" version of the repository only have the 0.3.2 version so i tried to build nyme-networkmanager from source myself on a PI zero but always get "Illegal instruction" at runtime. 

Is there special build inscrtruction on pi zero ?

**Comment by fbeauche** [comment]
I figured it out. I had to build dependecies (libnymea-networkmanager and libnymea-gpio ) from source as well to make sure it was in armv6 .

**Comment by mzanetti** [comment]
Right... Sorry, for raspbian buster we still haven't set up our build containers for armv6... 

And since the latest release, nymea-networkmanager has been split into a lib and the service.

Also gpio support has been added so one can use the RPi's GPIO pins to connect a push-button that would advertise the service on Bluetooth for a while (in addition to the "Always" and "Automatic" modes). Hence the new dependency.

Glad your figured it out.
