### ISSUE TITLE
Bluetooth stops advertising after 1 minute

### ISSUE THREAD

**Issue by mvdhorst** [nymea/nymea-networkmanager#53]
While the bluetooth should advertise for 3 minutes, when no WiFi can't be made yet, it only does this for 1 minute and then stops advertising.
We are trying to configure multiple devices at once, but after configuring the first device, the second etc. can't be connected to anymore via bluetooth.
There is already a WiFi network configured on the device, but it can't connect to this network, could this be the cause?

**Comment by t-mon** [comment]
Could you share your configuration file? 

By default there is the offline mode configured, which makes the bluetooth server only run while the system is offline. Once you connect to a wifi and you are online, the Bluetooth server shuts down, since your are online and the job is done.

If you want to configure multipe wifi networks in a row, you could either:
* Start with the always mode and the bluetooth server will run always (not very clean solution, since it anybody could reconfigure the device to connect to an other wifi)
* Starting the bluetooth server using the button mode on a gpio. Thi woul make it possible to start the bt server on demand, independent from the online state and you could restart the server how often you want and configur as many network as you want. This would be the most secure and clean way I guess.

**Comment by t-mon** [comment]
The default value is 60 seconds because all those modes exist only due to community requests. We use parts of the project in a product, where we start the server on button press event, advertise for 60 seconds which is enough time for the app to connect and following the wizard. 60 seconds is the perfect timeout for this scenario. 

You could deploy a default configuration with your mode and timeout settings, so you don't have to start the daemon with custom  command line parameters, or even mess with the systemd service which would get overwritten on an update.

Alternatively you can override the systemd service  in an override file for the daemon.

Feel free to close the issue if your issue has been resolved.

**Comment by t-mon** [comment]
Out of curiosity, for what are project are you using the daemon?

**Comment by mvdhorst** [comment]
We are using the daemon on our wireless care units, they are equiped with a Raspberry, and are configured with a forked version of the configure app, where we made it possible to configure multiple wireless care units at once.
